export const GET_GENREFANCYITEMS = 'GET_GENREFANCYITEM';
export const GET_FANCYITEMDETAILS = 'GET_FANCYITEMDETAILS';
export const SET_CURRENTGENRE = 'SET_CURRENTGENRE';
export const SET_LOADING = 'SET_LOADING';
export const GET_SEARCHRESULTS = 'GET_SEARCHRESULTS';
export const SET_DESKTOP = 'SET_DESKTOP';
export const SET_MOBILE = 'SET_MOBILE';
export const SET_TABLET = 'SET_TABLET';
