export const UPDATE_FIELD = 'UPDATE_FIELD';
export const SET_RECIPE = 'SET_RECIPE';
export const UPDATE_SEARCHSTRING = 'UPDATE_SEARCHSTRING';
export const UPDATE_SEARCHRESULTS = 'UPDATE_SEARCHRESULTS';
export const CLEAR_SEARCHRESULTS = 'CLEAR_SEARCHRESULTS';
export const UPDATE_PRODUCTINQUOTE = 'UPDATE_PRODUCTINQUOTE';
export const CALCULATE_RECIPERMQTYCOST = 'CALCULATE_RECIPERMQTYCOST';
export const CALCULATE_RECIPEEACHBRRMQTYCOST =
  'CALCULATE_RECIPEEACHBRRMQTYCOST';
export const CALCULATE_RECIPETOTALBRRMQTYCOST =
  'CALCULATE_RECIPETOTALBRRMQTYCOST';
export const CALCULATE_RECIPEFINALBRRMQTYCOST =
  'CALCULATE_RECIPEFINALBRRMQTYCOST';
export const CALCULATE_QUOTEFINALQTYCOST = 'CALCULATE_QUOTEFINALQTYCOST';
export const UPDATE_PRODUCTUNIT = 'UPDATE_PRODUCTUNIT';
export const SHOWHIDE_PRODUCT = 'SHOWHIDE_PRODUCT';
export const SHOWHIDE_BASICRECIPE = 'SHOWHIDE_BASICRECIPE';
