export const SET_LOADING = 'SET_LOADING';
export const SET_CATEGORYDATA = 'SET_CATEGORYDATA';
export const SET_DMENUPRODUCTDATA = 'SET_DMENUPRODUCTDATA';
export const SET_SLECTEDCATEGORY = 'SET_SLECTEDCATEGORY';
